### ISSUE TITLE
jar task is easily confused after uber generated multiple pom.properties files

### ISSUE THREAD

**Issue by schmir** [boot-clj/boot#112]
the jar task searches for pom.properties files in the fileset and chooses the first one in order to build the jar's name from it. The first one is pretty much random on my windows system, so I end up with a jar file name of one of my dependencies. As a workaround I can specify the filename via the file argument.

**Comment by micha** [comment]
Can we assume that `pom.{properties,xml}` files will be in the `META-INF` subdirectory of the the JARs being pulled in by `uber`? If so perhaps we just want to ignore anything in `META-INF` when we unpack the JARs into the fileset?

**Comment by schmir** [comment]
I'd rather vote for making it explicit. Or, is there a way to associate metadata to individual entries in the fileset? If not, probably there should be a way to do that.

**Comment by micha** [comment]
There definitely is! You can use the `boot.core/add-meta` function to associate metadata with entries in the fileset.

**Comment by schmir** [comment]
@micha thanks for the pointer.

I think the :exclude pattern for the META_INF directory does not work on windows, since it uses a slash character instead of a backslash. Will open an issue for that one.

Why does it exclude that directory by default?

**Comment by micha** [comment]
@schmir It excludes that directory because the stuff in it is only pertinent to the packaging of the jar, not to the code contained within (it's meta information about the jar itself), so when you make an uberjar that meta information is not relevant.

**Comment by schmir** [comment]
I'm reading that pom files from dependencies at runtime in order to print the version of packaged dependencies.

**Comment by jeluard** [comment]
I noticed this happen when `uber` task is used with some `:exclude` patterns. There is then an extra debug line `duplicate entry: META-INF/MANIFEST.MF` right after `Writing ... .jar` from the jar task.

It appears this is because setting your own `exclude` overrides default and `META-INF` from various libs collide.
I am not clear if this is on purpose or not. Maybe the default could still apply when you provide your own excludes? Or `META-INF` from libs could be relocated somewhere?
