### ISSUE TITLE
Consider renaming temp file functions

### ISSUE THREAD

**Issue by DomKM** [boot-clj/boot#128]
Warning: This is just a nitpick about naming.

I was reading the wiki (which is excellent!) and came to the [filesets page](https://github.com/boot-clj/boot/wiki/Filesets). The names of a few of the temp file functions stood out to me.

There's `temp-dir!`, `tmpfile`, `tmpdir`, `tmpget`, `tmptime`, and `tmppath`. This seems inconsistent both in terms of temp file functions and in terms of other core functions:
* one public temp file function is named `temp` while the rest are named `tmp`
* all public core functions are named with kebab-case except for all but one of the temp file functions

For consistency, I would consider renaming `temp-dir!` to `tmp-dir!` and renaming all of the `tmp*` functions to `tmp-*`.

It's a nitpick, but I figure it's better to pick before 2.0 is final.

**Comment by alandipert** [comment]
How about we add `tmpdir!` and deprecate `temp-dir!`?  This doesn't solve kebab-case, but maybe that remaining idiosyncrasy helps the functions look that much more related :-)

I fear it might be too late for a comprehensive change that included kebab-casing - we have pretty good momentum going, which I am worried would be diminished by breaking changes at this stage.

Of lesser impact would be additions and deprecations, but I'm hesitant about that too because it would be weird, and maybe confusing to people forever, to go into 2.0 with deprecations already.

**Comment by micha** [comment]
:+1: for the `tmpdir!` option here

**Comment by martinklepsch** [comment]
Would be weird to have `tmpdir!` but `cache-dir!` (probably there are more).

Maybe instead of just changing it it'd be good to start showing some deprecation notice in a release after 2.0 and deprecate it after that?

**Comment by DomKM** [comment]
@alandipert `tmpdir!` is certainly a change in the right direction (less inconsistency) but I agree with @martinklepsch that having `tmpdir!`, `tmpdir`, `cache-dir!`, etc. coexist is a little weird. I still advocate for renaming the `tmp*` functions to `tmp-*` and adding a deprecation notice to the `tmp*` versions. I wouldn't advocate this after 2.0.0 is released; if breaking changes are to be made I think they should be made now.

During normal use of Boot, I recently tripped on the changed signature of the pom license option and the complete change of what `merge-env!` does. It seems that both of these changes were made without a deprecation notice (which is fine!) and updating old code for these changes is more involved than a regex replace (as is the case with the `tmp*` -> `tmp-*` change). So, based on my (limited) experience of Boot API stability pre-2.0.0, I would consider renaming these functions for consistency to be a legitimate API change.

**Comment by martinklepsch** [comment]
Yeah, adding a deprecation notice now and deprecating it when 2.0 is final is probably a better way than what I suggested.

**Comment by alandipert** [comment]
Thanks everyone for the thoughts!

Let's go with the facelift that @DomKM proposes and deprecate everything we supersede.  Deprecated Vars should be marked with `^:deprecated` meta and where possible should print a `util/warn` deprecation notice that prints the suggested replacement.  We should also use this opportunity to audit the rest of the public functions in Boot to ensure they use consistent prefixes and are appropriately kebab-cased.

We can decide later, in 2.0 or beyond, if/when we actually want to remove the deprecated Vars.  In the meantime we can direct our efforts to updating documentation and public community projects to use the new names.

We should also take this opportunity to audit the rest of the public functions in Boot.

Any PRs to these ends would be graciously accepted.  Feel free to associate them either with this issue or to create new, more focused issues.  Otherwise, I'll get to doing this myself eventually.  Thanks in advance for help!

**Comment by DomKM** [comment]
Thanks for considering and approving this, @alandipert.

I will work on a PR for this next week.

**Comment by micha** [comment]
Fixed in 26fd3d5042917808a9718c2484f5f0432f114a6a c9a93d00670fbe5565e49fa6842306656c1f78d3 0f22ad2250db92638b4d98bd495fefafbe1ff143 e567d47c1fb70787ee7b7d1718b6251ad2503995 3ad9dfee4f119aa9dc722165cf8ad274cd2b816a 9493ac621132f74bac9276e5be2521444f544016
