### ISSUE TITLE
Consider adding visual notification task

### ISSUE THREAD

**Issue by DomKM** [boot-clj/boot#129]
Visual notifications are a very common feature request for Leiningen plugins (judging from my observation of IRC and Twitter conversations). I haven't seen any requests for audio notifications.

Please consider merging the built in `speak` task with @jeluard's [boot-notify](https://github.com/jeluard/boot-notify) to create a single built in `notify` task with `audible` and `visible` options. Thanks!

**Comment by martinklepsch** [comment]
I think the main blocker for something like this is the fact that it requires external dependencies to be installed.

**Comment by alandipert** [comment]
Maybe if you don't have the things installed it still works, but prints the message and installation instructions to console?

We could also bundle the different platform executables in our jar as part of the boot distribution and exec them from a tmpdir... too crazy?

**Comment by martinklepsch** [comment]
> Maybe if you don't have the things installed it still works, but prints the message and installation instructions to console? 
 
I think this would be ok. I.e. if users use the `(notify)` task and the required binary cannot be found print a warning & installation instructions but don't crash.

**Comment by DomKM** [comment]
> I think this would be ok. I.e. if users use the (notify) task and the required binary cannot be found print a warning & installation instructions but don't crash.

Agreed, except that `notify --audible` should still work without external dependencies required by `notify --visible`.

**Comment by Deraen** [comment]
`user=> (sh "notify-send" "hello world")` should work fine most of the Linux users without any external deps.
http://apple.stackexchange.com/questions/57412/how-can-i-trigger-a-notification-center-notification-from-an-applescript-or-shel Might this work for OS X?

**Comment by jeluard** [comment]
`notify-send` is already used on Linux while a similar command is used on Mac OSX. I believe this is what @martinklepsch was referring to as external dependencies.

I agree it would be convenient to merge both visual and audible notification in a builtin task.

**Comment by alandipert** [comment]
Does anyone have an objection or other thoughts on the following?  Tried to roll up this thread:

* `speak` takes `-a/--audio`, `-v/--visual` options; defaults to both
  * using these instead of `audible` and `visible` because they're a little shorter and at least as descriptive
* `--visual` prints a link to a Wiki page with platform notifier installation instructions, and the message, if a notifier isn't found
* we stick with slightly-weird but memorable-enough `speak` instead of renaming to `notify`
  * non-breaking
  * keeps the juicy `notify` name open for users to use as their own task name

**Comment by micha** [comment]
@alandipert :+1: i like it!

**Comment by martinklepsch** [comment]
> instructions on wiki so we can update them without pushing new release

actually see a benefit in coupling this with version control/releases.

Other than that :+1:

**Comment by alandipert** [comment]
@martinklepsch what benefit do you see to versioning the 3rd party software install instructions?  I see it as a downside because we don't actually control any notification tool source, and so can't incorporate how to install any of them into our own schedule.

**Comment by martinklepsch** [comment]
Sorry should've expanded on that.

My thinking was that what need to be installed basically boils down to
putting something on your path. And boot calls that thing.
>
>
When we change what boot uses in a later version we will update the wiki
page. People using older versions will get to the wiki page and install the
thing for a newer version of boot than the one they're using and it won't
work.

In my understanding the message to be printed is basically a link to some
tool that should be installed on a given platform. So fairly simple content.


-- 
—
Martin
http://martinklepsch.org <http://martinklepsch.org?ref=email>

**Comment by alandipert** [comment]
Ah ok I see what you mean.  I was thinking the wiki page could have the instructions for all versions.  That way we could update the instructions for old versions of boot if we needed to.

**Comment by DomKM** [comment]
@alandipert I like the proposal but I find `speak` to be a confusing name for this task. Perhaps something like `alert` would be better?

Or, what if we called it `notify` but made it higher-order, so users were able to pass in their own notification functions and Boot shipped with built-in notification functions for audio and visual notifications?

**Comment by micha** [comment]
@DomKM I haven't found higher-order tasks to be that useful in boot, because tasks compose so well on their own. The nice composition means you don't need to make tasks that shim in other tasks. Tasks can, of course, use the same underlying functions that the `speak` task uses if they want to, thereby "embedding" the `speak` task functionality in themselves. So instead of making a higher-order notification task, you can just make your task and have it use the underlying machinery of the `speak` task in addition to its own code.

**Comment by alandipert** [comment]
Thanks everyone for the input!  Here's what we're going with:

* `notify` takes -a/--audio, -v/--visual options; defaults to both
  * --visual prints a link to a Wiki page with platform notifier installation instructions, and the message, if a notifier isn't found
* `speak` is deprecated - it prints a message and calls the next task

A PR for the above would be graciously accepted.  Otherwise, I'll come up with one in a little while.

**Comment by jeluard** [comment]
Maybe it is the opportunity to reconsider `boot.core/*warnings*`usage as highlighted in this [discussion](http://hoplon.discoursehosting.net/t/best-practices-for-creating-extensible-tasks/358/7) ?

**Comment by micha** [comment]
I like the idea of adding warnings as metadata to files in the fileset, via an agreed-upon key, like `:warnings` or something. This would be a map entry conjed onto `TmpFile` records in the fileset. Tasks would use `boot.core/add-meta` to do this, probably.

The speak task could still get a count of warnings by just spinning through the fileset and counting the files with `:warnings` metadata on them, so it would work pretty much the same way.

**Comment by alandipert** [comment]
We released 2.0.0 and this ticket missed the boat so `speak` is here to stay.  We can still deprecate it, though.

**Comment by alandipert** [comment]
Closing as torch is carried by #226
