### ISSUE TITLE
Can't manage to make repl :init-ns work

### ISSUE THREAD

**Issue by jeluard** [boot-clj/boot#139]
I can't manage to make repl `init-ns` option work. I always end up in either `boot.user` or `user` ns.

e.g. with `boot repl -n some-ns` I end up in the `user` ns while with `boot repl` in `boot.user`
When using the `repl` tak in some other task I always end up in the `boot.user` ns no matter what ns I specify.

**Comment by micha** [comment]
Are you sure you can do `(require 'some-ns) (in-ns 'some-ns)` successfully?

**Comment by micha** [comment]
For example in the boot project directory i can do:

    $ (cd boot/pod && boot -s src repl -n boot.file)

and it works fine. Being dumped into the `user` namespace usually means something went wrong when loading the init namespace. The nREPL middleware falls back to `user` namespace in that case but sometimes isn't able to tell you what the problem was.

**Comment by jeluard** [comment]
Right `require` indeed failed because of some dependency on ClojureScript internals. Strangely it worked with leiningen, probably a nice side-effect of dependency isolation!

I managed to have the proper message (including the switch to user) when my code generates compilation errors (behavior triggered by this [code](https://github.com/trptcolin/reply/blob/master/src/clj/reply/eval_modes/nrepl.clj#L103) from reply ). My original issue was related to invalid ns definition. Any idea if this could be addressed at the boot or reply level? Would be nice to have boot provide feedback.

**Comment by micha** [comment]
Yes, I think the REPL setup in boot can definitely be improved, and it's really annoying when it swallows exceptions like that. Do you have any recommendations? I don't feel that great about the nREPL middleware hackage in the `boot.repl-server` namespace :smile:

**Comment by jeluard** [comment]
Can this exception be intercepted when starting the server? If yes I would say the best option is to stop there? I am not very familiar with nREPL so not sure if that makes sense, I might be plain confused :)

Regarding boot and the `repl` task I find it confusing to mix both client and server concepts. I believe this comes from leiningen?
One example of this is `(repl :client true)` and `(repl :server false)` which where not doing what I was expecting. I would rather have `(repl-server :server-options)` and `(repl-client :client-options)` now I might be missing the big picture here too.

**Comment by micha** [comment]
This solution isn't as slick as it could be because it only prints the stack trace to stderr on the nREPL side (it doesn't send the output back to the REPL client as it should), but it's better than nothing. If you know more about how to send the error message back to stderr via the nREPL client please reopen!
