### ISSUE TITLE
Improve sift :move when dealing with multiple files

### ISSUE THREAD

**Issue by jeluard** [boot-clj/boot#144]
I'd like to move all files matching a regexp to some folder but fail to do it in a single `sift :move`. It looks like regexp are pre-processed.

I can move complete directory content with `(sift :move {#"css/" "assets/"})` but apparently cannot move a subset of files (e.g. `(sift :move {#"css/.*\.css" "assets/"})`).

Strangely `(sift :move {#"css/*" "assets/"})` moves all files but `(sift :move {#"css/." "assets/"})` moves all files with their name chopped off the first letter.

**Comment by micha** [comment]
Sorry for the late reply...

I think you want to use [backreferences][1] there.

Can you please try something like this:

```clojure
(sift :move {#"css/(.*)" "assets/$1"})
```

Does that solve the problem?

[1]: http://docs.oracle.com/javase/tutorial/essential/regex/groups.html#backref

**Comment by jeluard** [comment]
Good point! Yes that works perfectly.

So is the expectation that `sift` source and target must refer both to a file or a folder but no mixed type? Are folder identified by trailing slash?
Also I am wondering how `#"css/*"` and `#"css/."` can not fail as they are not valid regexes.

Nothing really important, just trying to help making `boot` even more awesome ;)

**Comment by micha** [comment]
Yes, the fileset is similar to a git repository in that directories don't exist&mdash;it uses content-addressed blob storage internally.

**Comment by micha** [comment]
The `#"css/*"` and `#"css/."` regexes look valid, at least:

- `#"css/*"` should match strings `"css/"`, `"asdf/css"`, `"css/asdf/qwer"`, `"css////qwer"`, etc.
- `#"css/."` should match the same as `#"css/*"`, except for `"css/"` for example (the dot doesn't match)

**Comment by jeluard** [comment]
> it uses content-addressed blob storage internally

Ok I will need to dig that more to fully understand!

> The #"css/*" and #"css/." regexes look valid, at least:

My bad, spoke too fast.

Everything works fine then!

**Comment by micha** [comment]
The content-addressed blob storage thing is just the way boot makes the files in the fileset immutable. When you add a file to the fileset it copies that file from the directory where it currently resides into a special directory managed by boot, the "blob storage" directory. The name of the file in this directory is the MD5 hash of its contents. So this blob dir might look like this:

```
blobs
├── 1623840abbb9ae09a64a9aef65998ee3
├── 1c5cb9705c250ba53fdaa06e9d29b5eb
├── 310b9bab200cc654a8d3dd865f36f537
├── 3913dc84bc65685a6aee68a746d072b2
├── 3f0d4a8c41ae9959833e29f79439df90
├── 78ead5ea164bca3d5d8f048817962a5b
├── 81145431caaf1d5202583048a5adfa75
└── c63dc4c11941d30ec2d885f9e6021c35
```

All of the files in this directory are given read-only permissions; they're made immutable (as far as is possible given platform limitations).

The fileset object is where the mapping of relative path to blob id is made. Given this information a class path can be created (via the `boot.core/commit!` function) at any time, bringing the filesystem in sync with the immutable fileset object.

Because blobs are immutable they can be addressed by their MD5 hashes, but directories don't really fit this model very well, so we simply ignore them and create and destroy them as necessary to reproduce the file structure stored in the fileset object.

**Comment by jeluard** [comment]
Thanks that was very informative!

Am I right saying the `target` folder is completely recreated per each task execution? Would it be feasible to only overwrite files that effectively changed in the case of the same task being re-executed?
Alternatively could using a ramdisk for the blob storage and/or the target folder help with perf? On my machine for trivial task execution it looks like most of the time is spent copying files.

Also I think it would help to have a wiki page describing at high-level the execution of a task and how pod/fileset/task and env relates. The wiki is really great but pretty detailed and it would help to glue everything together.

Sorry this issue completely derailed.. Thanks for the awesome work! Boot is definitively a game changer.

**Comment by micha** [comment]
Thanks for the kind words and all your help :)

Boot should be computing the diff and only applying necessary changes when it copies files into the target directory. It's rewriting files that have only their modification times changed in addition to files that have their contents changed, so that might be an issue you're running into? 

In general, tasks should try to preserve modification times when appropriate, but sometimes they don't. If you can find the problem tasks we can fix them.

We were considering having the default target dir be `nil` or `/dev/null`, but as it is you can use the `-t/--target` option to boot to set it if you run into trouble (like for example if the CWD isn't writeable by your user). For example:

    $ boot --target /dev/null task1 task2

**Comment by micha** [comment]
Whoops, updated comment ^^

**Comment by jeluard** [comment]
Great! I will do some more investigation and let you know what I find.

+1 for not having a default target, or just having a dedicated task to copy to target. It seems like a source of confusion for newcomers.

**Comment by arichiardi** [comment]
@jeluard @micha 
I needed this and implemented a solution that can be added as `sift` action (after polishing of course)

```
(core/deftask rebase
  "A task for moving marked fileset from one dir to another, specified in the options."
  []
  (core/with-pre-wrap fileset
    (let [files (remove :boot-cljs-src-pre-fs (core/ls fileset)) <- make it generic
          paths (map (juxt :path #(str "cljs-src/" (:path %))) files)] <-this is the output dir
      (core/commit! (reduce (fn [acc [from-path to-path]]
                              (merge acc (core/mv acc from-path to-path))) fileset paths)))))
```

**Comment by arichiardi** [comment]
Gist: https://gist.github.com/arichiardi/45debef5d84934835555
