### ISSUE TITLE
Boot watch changed fileset with regex filter

### ISSUE THREAD

**Issue by johnwalker** [boot-clj/boot#241]
Hi, I'd like to be able to pass boot's watch fn a regex so that it only calls its handler when a file matched by the regex is changed. I have already written code that does this, and can put it in as a PR if you think it would be useful. Examples where this could be helpful is rerunning the clojurescript compiler only when a cljs or cljc file is changed.

I realize that a regex might be too particular, though. Passing predicates to the watcher is a bit more general. Another alternative is passing the changed fileset to the next handler inside the watch fn, which is the most general. Please let me know what you think.

**Comment by johnwalker** [comment]
Here is example usage code:

```clojure

(deftask cljsdev []
  (set-env! :source-paths #{"src" "test"})
  (comp (btr-watch :pattern #"\.cljs$")
        (cljs :source-map true :optimizations :none)))


```

**Comment by micha** [comment]
The general philosophy of boot is very different from make(1), for instance, or any of the dependency graph build tools. Boot takes the opposite approach: when the pipeline is run all tasks in the pipeline are called. However, each task is provided with managed temp directories in which they can keep track of their own state, and the immutable fileset abstraction allows for powerful fileset diffing capabilities. But the main idea is that each task manages its own caches, instead of having a global dependency graph that is managed externally by boot.

This has a number of advantages: tasks encapsulate their own dependency information (only the task itself can really know the relationship between source files and compiled artifacts, as this may not be a static relation, it may be dynamic and depend on the output of other tasks).

So the cljs task has its own private cache where it maintains state between incremental builds, and it also manages the cljs compiler caches. The cljs compiler shouldn't be compiling anything unnecessarily; it should be smart enough to only recompile namespaces that are newer than the corresponding compiled js. If this isn't the case then there is a bug with the cljs task or the cljs compiler, or there is something that's unexpectedly resetting the lastModified date of source files.

**Comment by johnwalker** [comment]
In that case, is there a way to get the changed files without the watch task passing them explicitly?

**Comment by johnwalker** [comment]
Oh, are you saying that the cache already has this information?

**Comment by johnwalker** [comment]
OK, I see how this works. The wiki is really well put together.

**Comment by johnwalker** [comment]
Thanks!
