### ISSUE TITLE
Add better support for interactions with refactoring and editor tooling

### ISSUE THREAD

**Issue by micha** [boot-clj/boot#251]
See clojure-emacs/refactor-nrepl#97

What these tools need to be able to do:
- ??
- ??

**Comment by expez** [comment]
* `find-symbol`, `find-unbound`, `extract-definition` and `clean-ns` slurps the content of a file in a read-only manner.
* `rename-file-or-dir` slurps files on classpath and also writes them back out, to update references to files which have been moved.  

This discussion was triggered by another hack in `rename-file-or-dir`: it looks at the directories on classpath to find the prefixes to source directories when creating the namespaces of new files (e.g. to make sure the ns is `my-project.some.ns` instead of `src.clojure.my-project.some.ns`)

**Comment by danielsz** [comment]
:+1: @expez

**Comment by micha** [comment]
Blocked pending concrete, actionable tasks.

**Comment by expez** [comment]
I need read/write access to files on the classpath for clj-refactor.

**Comment by Deraen** [comment]
You should be able to get list of the original source dirs with boot get-env:

```
boot.user=> (into (get-env :source-paths) (get-env :resource-paths))
#{"src" "resources"}
```

Then you can try to find the file inside those dirs by their relative paths. If the file doesn't exist there, it is created by some Boot task and editing it doesn't make sense.

**Comment by martinklepsch** [comment]
I think this has been solved with the introduction of `fake.class.path`? 

Related https://github.com/boot-clj/boot/issues/524 & https://github.com/boot-clj/boot/issues/632. Closing.
