### ISSUE TITLE
Clojure project spec (Gemspec analog)

### ISSUE THREAD

**Issue by kirillsalykin** [boot-clj/boot#293]
Hi,

Not sure if it is a good idea or i am just not have enough knowledge...

Anyway, i faced the problem:
I want to fork https://github.com/lamuria/clj-mailgun, extend it and try in my other project.

There is no way how i can specify github url in "dependencies". (If i understand correctly only published/built can be listed in "dependencies" section)

The only way how i can make it work - clone manually and add "clj-mailgun/src" path to :source-paths:
(set-env! :source-paths   #{"src", "../clj-mailgun/src"})

I am not sure if it's OK, but it works.

I guess it would be good (and i'll try find time to implement it) to have a Boot task which clones github repo and adds src to the source-paths.

But, the cloned project can be either Lein or Boot (or someday another tool will be added) and the task should parse it, find deps and resolve them.

In the ruby world gemspec exists - unified way to describe what the gem is about: name, deps, author etc. It looks a lot like Lein project.clj.

So, what i am proposing - it would be really nice to add something similar in clojure world (at least i think it can simplify things a lot).

cljspec?

What do you think? Does this sound sane to you?

**Comment by Deraen** [comment]
There is already a universal way to describe a project used by Java and Clojure (both build tools): POM files.

Back the the real problem: Using local version of external libraries in development while making changes to the external library.

This is supported by Leiningen and Boot checkouts (they solve the same problem in quite different ways).

In the project which depends on `clj-mailguin` you can add `checkout -d clj-maingun:0.2.0` to your Boot command (or similar task to your `build.boot` file). Then, each time the clj-mailgun jar-file in your local Maven repository (`~/.m2` folder) is changed, the new source files are added to the project and thus you can use latest source. In the library project you need to build a jar and install it to local Maven repository. With Leinigen you can do this with `lein install` and with Boot you would do something like `boot watch build-jar`.

**Comment by crisptrutski** [comment]
Checkouts are awesome for making the changes, but wondering if your question doesn't also cover distribution:

You've forked `boot speak` to output `cowsay`, but you can't wait for the maintainers to chew things over - you want to push out apps using this to pasture before the cows come home. :cow2:

Just as bundler support git repo co-ordinates (not something rubygems understands at all), maven's folksy architecture astronauts like to roll foreign code in on [wagons](http://maven.apache.org/wagon/). There's no `.pom` vs `.gemspec` envy necessary :smile: 

Not sure if boot supports adding wagons, but [wagon-ssh-external](org.apache.maven.wagon/wagon-ssh-external) or [wagon-git](https://github.com/synergian/wagon-git) could be be your ticket once that's there.

**Comment by crisptrutski** [comment]
@kirillsalykin one thing to mention though, is that in anger worth just running your own [gem](https://github.com/geminabox/geminabox) or [maven](https://archiva.apache.org/index.cgi) server to host your forks without fuss

**Comment by Deraen** [comment]
Interesting, though with a very quick glance it looks to be that Wagon-git (possible Wagons in general) requires that the artifact (i.e JAR file) is pushed to the Git repository?
I think it's nearly as simple to just change groupId and push the forked artifact to Clojars and use that.

**Comment by crisptrutski** [comment]
One difference that can matter there is privacy - either you can't legacy or competitively share your code, or you're just embarrassed :wink: 

Hadn't realised the wagons need to contain the JAR, that makes it a bit of a squib. With workarounds often bringing advantages also, not sure how valuable throwing more tooling at the problem is for now.

**Comment by kirillsalykin** [comment]
@Deraen @crisptrutski Thanks for answers i learned new things from them, but i have slightly different question :)

Currently clojar MUST be a jar (and it will have the pom.xml in that case).
But there is no way how you can distribute you clojar as clojure source code.

Please compare with ruby/gem - all gems are actually source code (zipped).

And my question: - is there way to distribute clojar as source? 
In that case it would minimize java/maven dependency. 
And theoretically same packages can be used for clojure/clojuerscript/clojure.clr etc.

It will increase build time, but jar files can be cached.

What do you think about it?

**Comment by Deraen** [comment]
Jar is a zip file and in Clojure's case it contains the source code so in fact this works very similarly to Ruby.

But no, there is no way to (currently) distribute Clojure code without packaging it in Jar. And it's not also objective of this project to offer such possibility. All Clojure tooling currently builds on top of Maven infrastructure and libraries and it would be huge effort to change that.

**Comment by kirillsalykin** [comment]
@Deraen thanks for clarification!

I am still learning, sorry for stupid questions.

**Comment by kirillsalykin** [comment]
@Deraen i guess i can close the issue? Or shall we ask for wagon-git support?

**Comment by crisptrutski** [comment]
Think we can close - [it looks like wagon support is already in boot](https://github.com/boot-clj/boot/wiki/S3-Repositories)

**Comment by kirillsalykin** [comment]
@Deraen @crisptrutski Thanks!

**Comment by martinklepsch** [comment]
@kirillsalykin don't worry about asking "stupid" questions, all questions are welcome here 😊

**Comment by jeluard** [comment]
@kirillsalykin  Actually the analogy with GEMSPEC is pretty interesting. It would be definitively valuable to have a standard way to define basic project structure like source folders and dependencies.

A concrete issue is that so far no build tool support `build.boot` which forces all projects to define an extra `project.clj`. This is obviously something we want to improve.

**Comment by micha** [comment]
@jeluard That assumes that the project _can_ be described with a static map, but this is not necessarily the case with boot because boot builds are part of your program, so there isn't a way in general to describe a boot build declaratively.

**Comment by kirillsalykin** [comment]
@micha i guess it is not about the build process itself, but about project description: just name, version and dependencies (maybe author and description).

I do like the ruby approach in this: gemspec to describe and rake to do work.

**Comment by micha** [comment]
@kirillsalykin the best thing to do there is to make a pom.xml file and JAR.

What you are trying to do is equivalent to specifying the output of a computer program statically, without running the program, because the parameters of the "project" are all computed dynamically by tasks at runtime. This is impossible due to the halting problem.

There is no built-in Project abstraction in boot, even, because what a project is is not a thing that anyone can really describe in a static map of key value pairs. A project to me will be different than to you, and this is what makes boot powerful. What you see as the "project name" is really only relevant to making a pom.xml file, which in turn is usually used for interop with Maven.

To put it another way, boot isn't even a build tool, it's simply a way to bootstrap you into a place where you can run Clojure code, and a set of library functions that you can use in the Clojure program you write to do things like created pom files and JARS and add dependencies to your classpath, etc.

I definitely don't prefer building things with Rake, and the reason why is because like Make, Leiningen, etc. it's declarative. I need to be able to program and not just fill in forms for a build tool configuration. Like I need to do things that boot doesn't even know about-- use it in ways boot wasn't expecting. This is really hard to do with declarative build tools because you need to express the details statically, not dynamically, so every permutation needs to be supported by the existing tool.

**Comment by kirillsalykin** [comment]
@micha i got your point, you are totally right.

**Comment by jeluard** [comment]
@micha I wasn't suggesting such a spec should replace `build.boot`. Surely it's not all or nothing and thanks to `boot` programmatic nature it could just be a function call away to read and preconfigure your build from a static file.
I don't see how `pom.xml` and JAR helps when it comes to load my project into my dev environment. Or are you suggesting a `pom.xml` can be generated from `build.boot`? It would still have to be manually synced (and I can just generate a `project.clj` this way).

A basic common spec defining main src folders, dependencies and something like profile that can be dynamically activated would come a long way and be beneficial for the whole tooling ecosystem.

**Comment by micha** [comment]
@jeluard Sorry if I'm being dense, but how could we make a static spec for something like this:

```clojure
(deftask foo
  [a awesome bool "Enable awesomeness mode?"]
  (when awesome
    (set-env! :dependencies #(conj % '[my.awesome/dependency "1.2.3"])))
  (with-pre-wrap ...))
```

What could we put for dependencies then? Or am I missing the point?

**Comment by martinklepsch** [comment]
I think @jeluard's point was that a file like this could suffice as a baseplate for multiple tooling approaches (lein/boot) while still allowing tools like boot to modify things later on.

**Comment by micha** [comment]
So what would we put in the `:dependencies` slot?

**Comment by micha** [comment]
What I do when I need a static representation of the build environment is something like this:

```
boot foo bar baz show -e
```

This outputs the env after any tasks have altered it. You get an EDN map, which is very similar to a Leiningen `defproject`. It seems like it would be easy enough to add perhaps a `--leiningen` option to the `show` task, so you could do:

```
boot foo bar baz show -l > project.clj
```

Would that do what you want?

**Comment by jeluard** [comment]
Right @martinklepsch summarized my point pretty well. Most projects (at least mine) have a static nature or could be modeled via something like lein's `profile` concept.
That is not to say it is sufficient for all needs and `boot` approach really shines here.

You could have something like this in `boot`:

```clojure
(load-base-configuration!) ; load some know file defining basic structure

..
; your regular tasks modifying deps, paths
```

Other build tool like `lein` could just load this file based on a convention. Obviously it only works if there is a global agreement between tooling implementers.

I didn't consider `boot show` and it looks like the right approach for cursive and co. Still it requires custom support for `boot` as opposed to free support if there is a common convention.

**Comment by micha** [comment]
@jeluard My point was that I think the right place to form a solution is in a task, not in boot itself. You can totally make a task that takes information from the `(boot.core/get-env)` map and combines it with other things or filters it as you like, and emits whatever you want to a file.

Suppose you call this task `dump-env`:

```clojure
(deftask dump-env
  [o output PATH str "The path to the output file."
   f format NAME kw "The output format (one of 'lein', ...)."]
  (with-pre-wrap fileset
    (let [env-map (process (get-env))] ; process could be some post-processing fn
      (spit (io/file output) (format-env format (get-env))) ; format-env could be a multimethod, perhaps
      fileset)))
```

Then you could use it like this:

```
boot watch foo bar baz dump-env -o project.clj -f lein
```

Now it can write the file containing the computed env, even in the dynamic case, and boot itself doesn't need to make any assumptions at all about how projects are built or what a project even is.

**Comment by micha** [comment]
Even in the declarative world of Make they do this, via autotools. Tools that dynamically generate a Makefile for you, querying programs like GCC to compute dependencies etc. I think this is definitely the most common way to deal with complexity, maybe the only way (I don't know of any other way really). Rather than restrict boot to the limitations of declarative tools, we should just let boot run your program and query it at runtime to extract its state.

**Comment by jeluard** [comment]
Sure I understand this is cleaner but then as a user I have to care about this sync process manually. Also I don't know how IDEs would support those dynamic external changes to `project.clj`. Multiplied by each individual projects that's a significant burden that doesn't bring much value to my simple projects.

I won't pretend my needs reflect the common `boot` user needs though.

**Comment by micha** [comment]
What do you mean when you say you have to care about the sync process?

The project.clj file wouldn't change unless your env changes from one incremental compile to the next, which is rare even for dynamic tasks. I haven't seen one that does this yet. Also I believe that things that are sniffing the project file or whatever probably account for changes to it (like I don't think you need to restart Cursive if you make changes to your project.clj file).

**Comment by micha** [comment]
Another data point, for completeness :)

The best way to interop with tools that are looking at the project.clj file is probably to just use the underlying functions those tools are using. Like make a task that has the Clojure code used by the tool to do its work as a dependency, and call into those functions from the task. Usually this can be done in a pretty straightforward way, and probably even easier since you have pods available, which gives you very fine-grained control over state (eg. you can replace a pod that contains stale state very easily and efficiently and avoid JVM startup costs whenever you like).

**Comment by jeluard** [comment]
I am talking about changing dependencies or paths (rarer). If cursive supports external changes to `project.clj` I could update my `dev` tasks to rely on your approach.
That sounds overkill but that could do it. I have to give it a try.

**Comment by micha** [comment]
And finally, there is nothing preventing the implementation of such a scheme:

_build.boot_
```clojure
(apply set-env! (mapcat identity (read-string (slurp "project.edn"))))
.
.
.
```

**Comment by jeluard** [comment]
Right this one I prefer but it only is useful if there is broad acceptance. Sounds herculean work to make the community reach such an agreement. I'll just pass my turn ;)

**Comment by micha** [comment]
I think maybe a good thing to think about is the comparison between the different "checkout dependencies" approaches used by eg. boot and Leiningen.

Checkout deps is the term for dependencies of some project that you are working on in parallel. For example maybe you have project A that depends on project B, and you want to work on both A and B at the same time. Without checkout deps you'd need to rebuild project B and restart A's build every time you make a change to B. With checkout deps your project is continuously rebuilt when you change either A or B, and the changes are reflected in the output of A's build.

* Leiningen does this by merging the B project into A and building both. This works but is fussy (you can have dependency conflicts because transitive dependencies of B are merged with A's dependencies, plugin conflicts, configuration issues you need to manage and debug).

* Boot does the opposite: in Boot project A consumes the project B JAR--no merging of the projects is attempted. The non-transitive dependencies of B are added to A, but that's it. You'd do it in two separate builds that run in parallel:
  * A `boot watch checkout -d B foo bar baz ...`
  * B `boot watch pom jar install`

The boot way avoids the need for A to know anything about how B is built. In fact, B can be built using Leiningen, Rake, whatever, as long as it can produce a JAR and install it to your local Maven repo.

This is what I was saying before about the pom.xml and the JAR. Here we have a concrete, static instance of a build, expressed in perfect fidelity via the standard project descriptor for Clojure: the pom. The dynamic nature of boot is not an impediment here, as we only deal with a specific result, not all possible results. And in the end you can accomplish the task with far less configuration and no boilerplate, at all.

I think this is a good model for external tooling to adopt. Consume a concrete artifact whenever possible. This is what we accomplish with the `dump-env` task: we emit a concrete project descriptor that is 100% correct at all times.

**Comment by yatesco** [comment]
(note - this is all theory, I haven't actually tried this!)

I really appreciate the cleanliness of this approach however, it does have some practical downsides (assuming I understand this right!); the number of processes increases worse than linearly with the number of dependencies. For example, it isn't unusual that I develop 4 projects in parallel:
 - a relatively new company wide shared library
 - the server component of the project 
 - the UI of the project
 - a project shared between the server and UI (think schemas in .cljc files for example)

With the leiningen approach I have 4 processes, one process for each project but through the use of checkouts and git submodules that is all I need. With the approach advocated here I would need:
 -  4 build processes
 - a `boot watch pom jar install` for each jar being depended upon
 - a `boot watch checkout...` process for each dependant per _instance_ of that dependant (i.e. one for the server->company-wide-shared dependency and another one for the ui->company-wide-shared dependency)
 
Is that right?

Or, can the two 'dependency magic' tasks be composed with the 'usual' boot tasks so in fact we are back down to one process per project, where that process is something like 'boot build-myself-and-watch-dependants'?

**Comment by martinklepsch** [comment]
> Or, can the two 'dependency magic' tasks be composed with the 'usual' boot tasks so in fact we are back down to one process per project, where that process is something like 'boot build-myself-and-watch-dependants'?

If by "dependency magic" you mean the `checkout` task then yes it can be composed like any other task.

As I see it you would want the following setup:

- a relatively new company wide shared library — `boot watch pom jar install`
- the server component of the project — `boot checkout ... run`
- the UI of the project — `boot checkout ... dev`
- a project shared between the server and UI (think schemas in .cljc files for example) — `boot watch pom jar install`.

**Comment by yatesco** [comment]
I see - thanks. 

So just to be explicit I would be adding in the usual development tasks to each of the four projects (test, eastwood etc.) but they can all be composed either in a `deftask` or on the command line.

Nice.

**Comment by martinklepsch** [comment]
@yatesco As long as your development tasks all comply with [Boot's definition of tasks](https://github.com/boot-clj/boot/wiki/Tasks) that works, yes.
