### ISSUE TITLE
Deploy boot.jar to Clojars?

### ISSUE THREAD

**Issue by martinklepsch** [boot-clj/boot#336]
Instead of downloading boot.jar from Github releases we could probably deploy it to Clojars and download from there. This would make deployment more streamlined.

URIs for jar's can be easily derived from ID and version: 
```
https://clojars.org/repo/boot/core/2.4.2/core-2.4.2.jar
``` 
Not sure if this is possible because it's an uberjar but really shouldn't make much of a difference?

**Comment by micha** [comment]
It's possible. I did this initially with boot1. I don't remember exactly what the issue was but when github releases became a thing I moved the binary to there. I'm not sure what the terms of service are for Clojars and uberjars, but I think I ran up against a maximum JAR size limit or something? (There was a bug in the makefile that was adding the previous uberjar to the next uberjar and that uberjar to the next one...it got pretty big before I noticed the problem.)

But regardless, `boot.sh` is finished and released. I don't think we want to change it to look in Clojars because that would break the existing version (unless we deploy to both places, which would defeat the purpose).
