### ISSUE TITLE
Backport GPG fixes from Lein

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#347]
GPG code was recently changed on Leiningen and we should probably port those changes to our implementation: https://github.com/technomancy/leiningen/issues/1892

**Comment by Deraen** [comment]
I did look into this but the new gpg call (https://github.com/technomancy/leiningen/commit/fb876c7d49201e4e1253e271abe4b4086a20439d) requires https://github.com/hyPiRion/com.hypirion.io and I'm not sure what would be best way to depend on that, or if it's even a good idea.

**Comment by hyPiRion** [comment]
@Deraen: Just a heads up here – we're using `com.hypirion.io` because we need to support java 1.6. The specific use case in the GPG code can probably be replaced with [`ProcessBuilder/inheritIO`](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html#inheritIO\(\)), at least that's what I am going to do if we weren't forced to support 1.6.

You should also be aware of technomancy/leiningen#2063 if you decide to follow up on this, as GPG calls that produce output obviously shouldn't redirect stdout.
