### ISSUE TITLE
silence target warning when target task is being used

### ISSUE THREAD

**Issue by jaredly** [boot-clj/boot#391]
it's really unnerving to have the `Implicit target dir is deprecated, please use the target task instead.` warning show up even when you *are* using the target task instead. took me way to long to trust that I was actually using the target task correctly.

**Comment by Deraen** [comment]
This wouldn't affect cases where target task is now being used.

I think it would be best to release breaking version which changes the default soonish.

**Comment by micha** [comment]
@jaredly The warning is perhaps confusingly worded. The intention was to warn that the _implicit_ target directory is deprecated, meaning the behavior of **automatically writing output files to a directory**. Using the target task does not disable this deprecated behavior &mdash; only setting the `BOOT_EMIT_TARGET` environment variable (or boot.properties setting) to `no` does. The warning tries to helpfully point the user to the new alternative to the deprecated behavior and suggests using the target task instead of relying on the implicit target directory.

**Comment by jaredly** [comment]
yeah, I understand that now (after a lot of head banging...) -- why doesn't using the target task disable the behavior? Seems like a reasonable thing to do

**Comment by micha** [comment]
Hmm... it could work that way. It seemed clearer at the time to separate the deprecated behavior from the new feature. In hindsight it does seem better for the target task to suppress the warning, especially since the warning mentions using it!

Probably too late now though?

**Comment by micha** [comment]
OK I think we should do this. Unless someone objects? This is perhaps a breaking change but I can't imagine anyone using both the target task and the implicit target dir at the same time...

**Comment by daveyarwood** [comment]
Sounds reasonable to me :+1:
