### ISSUE TITLE
BOOT_JVM_OPTIONS and BOOT_JAVA_COMMAND can't be set on boot.properties

### ISSUE THREAD

**Issue by Deraen** [boot-clj/boot#433]
Properties file is read by Java after the JVM is started so obviously these env variables can't be read by Java.

As these are the only env variables not support in properties file this is a bit confusing.

Perhaps it would be possible to implement special case in the wrapper script to read these two properties from properties files?

**Comment by esanmiguelc** [comment]
Hi all, I've been thinking about grabbing this one.

I think sourcing the `boot.properties` from `boot.sh` might be enough for this. 

Any thoughts?

**Comment by RadicalZephyr** [comment]
I think the only tricky part of this would be not overwriting environment variables specifying other properties that are also set in the `boot.properties` (like `BOOT_CLOJURE_VERSION`).

So maybe what you want to do is something like:
- `source "$BOOT_HOME"/boot.properties` from a subshell and return the read `$BOOT_JVM_OPTIONS` storing into a temp variable inside `boot.sh`
- same for `$BOOT_JAVA_COMMAND`
- use those values as defaults and read the same values (using a subshell again) from `./boot.properties`
- use the resulting values as defaults for reading the current environment variable values

Something like that should maintain the configuration priority order specified in the wiki.

The other thing I'm wondering about is whether the `BOOT_JVM_OPTIONS` from all three places should essentially be concatenated instead of being "highest priority wins"?  I guess it depends on how java treats repeated setting of system properties at the command line...

**Comment by esanmiguelc** [comment]
Started a branch where we can continue this conversation in the actual repo where these changes take place: https://github.com/boot-clj/boot-bin/pull/5

**Comment by martinklepsch** [comment]
https://github.com/boot-clj/boot/issues/433

**Comment by martinklepsch** [comment]
This has been fixed in https://github.com/boot-clj/boot-bin/pull/13 and will be part of the next Boot release.

**Comment by zalky** [comment]
Is this supposed to work in boot `2.8.1`? Setting `BOOT_JVM_OPTIONS` in the project `boot.properties` seems to have no effect. I must set the environment variables for it to work.

**Comment by zilti** [comment]
Same, doesn't work on `2.8.1` for me either, despite the wiki stating otherwise. I redownloaded boot.sh as well.

**Comment by zalky** [comment]
So it seems that the changes to make this work have not been rolled into a release of the boot binary yet. I guess until that happens, it doesn't matter what version of boot is used.

**Comment by danielcompton** [comment]
It looks like there is a new release https://github.com/boot-clj/boot-bin/releases/tag/latest which will provide this now.

**Comment by martinklepsch** [comment]
@danielcompton I’m afraid the respective PR was rolled back and thus is not part of 2.8.2 😞
