### ISSUE TITLE
macOS: boot 2.7.1 terminal hangs

### ISSUE THREAD

**Issue by pesterhazy** [boot-clj/boot#548]
Almost immediately after updating to boot 2.7.1, I see strange symptoms:

- opening a new iTerm2 tab hangs in the `login` process
- same with Terminal.app
- I can still open a terminal with `/bin/sh` set as the command
- when I run `login` in such a terminal, it hangs
- when I run `ps waux`, the process hangs after displaying a few processes

Normally I wouldn't suspect boot, but this happened for the first time immediately after the update, and I've heard similar reports from one other person.

When I run `killall -9 java`, everything starts working again.

Perhaps a ultimately a java problem?

```
macos 10.11.5
java version "1.8.0_51"
```

**Comment by martinklepsch** [comment]
I'm the other person mentioned. I had similar issues but already before the 2.7.0 release. Until now I never assumed it could be java or boot related but hearing this from another person I'm considering it a possibility. 

So far I haven't tried `killall java` to fix the issue but I'll give that a shot next time it occurs. Should it fix the issue we probably can assume it's related to Java in one way or another.

**Comment by martinklepsch** [comment]
So I just had this happen again and `killall -9 java` indeed fixed the issue. I'll try to understand why that is happening. In the meantime I've accumulated some more info (logs etc) in [this gist](https://gist.github.com/martinklepsch/f221b043cf53f659d955c49685072426).

Oh, and sorry about the title formatting haha.

**Comment by martinklepsch** [comment]
FWIW I also have this with a Leiningen project I'm working on so it seems more Java/Clojure related than Boot-specific. Still no clue why this happens though. 🤷‍♂️

**Comment by kennethkalmer** [comment]
Just to add a few pennies here in case someone else stumbles onto this issue... I had the same issue with lein, and it started without any changes to my system. I didn't upgrade Java, not any dependencies in the project, or lein itself.

I ended up testing with `java -version` and it just hanged. For some reason I thought it might be DNS resolution issue, so when trying to clear the DNS caches in macOS I got a different error that hinted to my system being in an inconsistent state (sudo didn't know who user 501 is).

I rebooted and everything worked just fine again. In my case it is like the window server in macOS crashes from time to time. If I don't see it happen I wouldn't notice it since I'm back at the login screen, login and continue. All the terminal processes are still running and it is just Chrome & Slack that reload fully, with Chrome complaining about having crashed...

**Comment by martinklepsch** [comment]
FWIW I either got really good at thoughtlessly working around this issue or it resolved itself. @pesterhazy @kennethkalmer did anyone of you run into it again more recently?

**Comment by pesterhazy** [comment]
Not me

**Comment by kennethkalmer** [comment]
It hasn't happened to me in a while, and when it does I just start opening new tabs in iTerm (starting new zsh sessions) and things work as usual...

That said, I'm not sure if this is a boot specific issue. Like I mentioned in my previous comment, even `java -version` wouldn't work

**Comment by martinklepsch** [comment]
Ok, so lets just say this resolved itself and if one of us runs into it again then we'll report back here? 

<strike>RT</strike> Close if you agree.

**Comment by pesterhazy** [comment]
🚪
