### ISSUE TITLE
refer to Windows support as experimental in documentation

### ISSUE THREAD

**Issue by alandipert** [boot-clj/boot#93]
As far as I know, none of the boot contributors so far use or deploy to Windows themselves, so Windows support is perpetually behind Mac and Linux.  Pending a Windows champion, it will likely remain that way.

I propose that we refer in documentation and READMEs to Windows support as "experimental".  This way users will have more realistic expectations, and Windows-based developers can recognize Windows support as an area boot could use help with.

**Comment by aadrian** [comment]
> Windows support as "experimental". This way users will have more realistic expectations

Sorry but I don't think so. Since it's the mostly used developer env, it's expected to work.  
They will simply not use Boot if this is mentioned in the docs: there are far too many projects that behave this way, and won't get adopted in companies (of course, except SF area) because of lagging or missing Windows support.

**Comment by alandipert** [comment]
@aadrian Do you think it would be better to say explicitly that Windows is not supported until the day that it is, should that day come?

Obviously it would be awesome if we attracted Windows developers and boot worked as well on Windows as it did anywhere else.  The people whose time I'm thinking about saving is people on Windows not interested in developing boot.  I would hate to waste their time, and be acquired as a sour taste, by setting expectations for them in documentation that will be inevitably unfulfilled only after they've gone through the trouble of installing.

At the same time, I would hate for a message of "Windows is unsupported" to be read by Windows developers as a statement that we're not interested in someday working on Windows, or otherwise not open to assistance in doing so.

**Comment by micha** [comment]
Perhaps we can somehow give Windows developers some incentive to help us support their platform?

**Comment by aadrian** [comment]
@alandipert I think a "sour taste" is still a taste, and it's still better than not trying Boot at all because of the warnings :).

I don't really think there's need for incentives: it's enough if the project tries to be as platform independent as possible, clearly separates what is platform dependent and can't be made otherwise, and also keeps it that way with later releases and new features.

Take a renowned project as a counter example: Meteor(.com) : community ported/adapted it several times for the Windows platform, still later features/upgrade broke that by adding even newer platform dependent stuff and assumptions into the code: even to this day is still not really working on Windows so most companies don't even have it on the Roadmap, so it's more hype than reality.

**Comment by ilazarte** [comment]
How is boot built and debugged as a tool?  I couldn't find anything on the wiki much less window specific info.  Tried the running the hello world commands (in windows style) on my work box, was saddened :(.

**Comment by schmir** [comment]
As I just said on IRC I'm now able to build a javafx based application, including building a standalone distribution with javapackager, and an installer with inno setup.

I can write some documentation about setting up a development environment for windows (I'm using mingw)...

**Comment by ilazarte** [comment]
That would be helpful, and I think would encourage windows dev to start looking to fill in the pieces.

**Comment by schmir** [comment]
I've started a wiki page here:
https://github.com/boot-clj/boot/wiki/Windows-Development-Environment
